[es]
host_ip = 127.0.0.1
host = http://localhost:9200
port = 9200
index = ''
doc_type = ''
request_timeout = 900
user = elastic
pass = n*kDT9cHvHlpP5QNJ2jS
host_mode = ip
bar_count = 50
#host = https://elasticsearch-coordinating-only.elasticsearch.svc.cluster.local:9200
#host = https://elasticsearch.elasticsearch.svc.cluster.local:9200
#host_ip = 94.182.179.220
#host_ip = 37.156.145.21

#user = a.daneshvar
#pass = B3QOqeyyYA94
#pass = hn#Tja^eEV

; [mongodb]
; host=65.21.64.202
; username=admin
; password=asdfzxcv1212
; database = link_agent
; port = 27017

[timezone]
country = Asia/Tehran
offset = +03:30

[chart_name]
users_logs = /logs

[user]
register_user = /register
update_user = /update
login = /login
get_list_users = /users
get_user = /user
delete_user = /user/delete